name: Release
on:
  push:
    branches:
      - canary
concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  canary-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
      - run: |
          yarn
          yarn build
          yarn kovan:deploy
          yarn export:all
          git config user.name GitHub Actions
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git diff --quiet deployments || (git commit -am 'generated' && git push)
          yarn version --prerelease --preid=canary
          yarn publish --access public --tag canary
          git push
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          MNEMONIC: ${{ secrets.TESTNET_MNEMONIC }}
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}